version: '3'
services:
  supernet-agent-manager:
    build: .
    command: uvicorn module_a.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
  supernet-agent-client:
    build: .
    command: uvicorn module_b.api.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"